# Generated by Django 3.1.5 on 2021-01-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sm_rx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtocustomerpostassaystatusrequest',
            name='status_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
