# Generated by Django 3.1.5 on 2021-01-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sm_rx', '0002_auto_20210108_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmtocustomerpostassaystatusrequest',
            old_name='status_update_time',
            new_name='status_update_time_db',
        ),
    ]
