"""
Django settings for lims_server project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ep123456781234567812345678123456781234567812345678'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# '2021-12-12T12:00:14.858000'
MY_DATETIME_FORMAT = 'YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]'

# my_datetime_format = 'YYYY-MM-DD_hh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z]'

REST_FRAMEWORK = {

    # 'DATETIME_FORMAT': 'iso-8601',
    # 'DATETIME_INPUT_FORMATS': ['iso-8601'],
    # 'DATETIME_FORMAT': MY_DATETIME_FORMAT,
    # 'DATETIME_INPUT_FORMATS': [MY_DATETIME_FORMAT],
    # 'DATETIME_FORMAT': MY_DATETIME_FORMAT,
    # 'DATETIME_INPUT_FORMATS': [MY_DATETIME_FORMAT],
    'DATETIME_FORMAT': 'blah5',
    #'DATETIME_INPUT_FORMATS': ['blah6'],
    #                          '2021-12-12T12:00:14'
    'DATETIME_INPUT_FORMATS': [r'YYYY-MM-DDThh:mm:ss', r"foo"],

    # 'DATE_FORMAT': 'iso-8601',
    # 'DATE_INPUT_FORMATS': ['iso-8601'],
    # 'DATE_FORMAT': MY_DATETIME_FORMAT,
    # 'DATE_INPUT_FORMATS': [MY_DATETIME_FORMAT],
    'DATE_FORMAT': 'blah1',
    'DATE_INPUT_FORMATS': ['blah2'],

    # 'TIME_FORMAT': 'iso-8601',
    # 'TIME_INPUT_FORMATS': ['iso-8601'],
    # 'TIME_FORMAT': MY_DATETIME_FORMAT,
    # 'TIME_INPUT_FORMATS': [MY_DATETIME_FORMAT],
    'TIME_FORMAT': 'blah3',
    'TIME_INPUT_FORMATS': ['blah4'],


    # 'YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].',
    # 'YYYY-MM-DD_hh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].']

    #'DATETIME_FORMAT': 'YYYY-MM-DDXXXhh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].',

    #'DATE_FORMAT': 'YYYY-MM-DDXXXhh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].',

    #'DATE_INPUT_FORMATS': [
    # 'YYYY-MM-DDThh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].',
       #'YYYY-MM-DDXXXhh:mm[:ss[.uuuuuu]][+HH:MM|-HH:MM|Z].']
    }

